spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: eternal
    password: pass
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

app:
  chat:
    jwt:
      private:
        key: classpath:keys/private.pem
      public:
        key: classpath:keys/public.pem
      expiration: 500

management:
  endpoints:
    web:
      exposure:
        include: mappings

server:
  error:
    include-message: always
