spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: eternal
    password: pass
  security:
    user:
      name: eternal
      password: pass
  jpa:
    hibernate:
      ddl-auto: update


server:
  servlet:
    context-path: /api/v1

app:
  chat:
    jwt:
      private:
        key: classpath:keys/private.pem
      public:
        key: classpath:keys/public.pem
      access-token:
        expiration: 15
      refresh-token:
        expiration: 30

management:
  endpoints:
    web:
      exposure:
        include: mappings
